# Generated by Django 5.0.8 on 2024-08-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_messages/')),
                ('transcript', models.TextField()),
                ('duration', models.FloatField()),
            ],
        ),
    ]
