# Generated by Django 5.0.8 on 2024-08-20 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0008_remove_imageanalysis_message_remove_message_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_messages/')),
                ('transcript', models.TextField()),
                ('duration', models.FloatField()),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_content', to='chat.message')),
            ],
        ),
    ]
