# Generated by Django 5.0.8 on 2024-08-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_interface', '0003_remove_documentmetadata_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmessage',
            name='document_hash',
            field=models.CharField(default=123456789, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
