# Generated by Django 5.0.8 on 2024-08-22 09:58

import django.db.models.deletion
import image_interface.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_messages/', validators=[image_interface.models.validate_image])),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('description', models.TextField()),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_content', to='chat.message')),
            ],
        ),
    ]
