# Generated by Django 5.0.7 on 2024-08-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_content_type_message_file_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='file_content',
            new_name='file',
        ),
    ]
