# Generated by Django 5.0.7 on 2024-08-19 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioanalysis',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audioanalysis', to='chat.message'),
        ),
        migrations.AlterField(
            model_name='imageanalysis',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imageanalysis', to='chat.message'),
        ),
    ]
