# Generated by Django 5.0.8 on 2024-08-20 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_audioanalysis_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageanalysis',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='No Text Data Found')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_content', to='chat.message')),
            ],
        ),
        migrations.DeleteModel(
            name='AudioAnalysis',
        ),
        migrations.DeleteModel(
            name='ImageAnalysis',
        ),
    ]
